builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "master-{{.ShortCommit}}"

