// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/manifest/provider.go

// Package mockManifest is a generated GoMock package.
package mockManifest

import (
	reflect "reflect"

	stevedore "github.com/gojek/stevedore/pkg/stevedore"
	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Manifests mocks base method.
func (m *MockProvider) Manifests(arg0 map[string]string) (stevedore.ManifestFiles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manifests", arg0)
	ret0, _ := ret[0].(stevedore.ManifestFiles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Manifests indicates an expected call of Manifests.
func (mr *MockProviderMockRecorder) Manifests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manifests", reflect.TypeOf((*MockProvider)(nil).Manifests), arg0)
}
