name: Master Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch go modules
        run: go mod vendor
      - name: Build and archive binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release -f .goreleaser-master.yml --rm-dist --snapshot
      - name: Vars
        id: vars
        run: |
          echo "::set-output name=short-sha::$(git rev-parse --short HEAD)"
      - name: Store release archives
        uses: actions/upload-artifact@v2
        with:
          name: stevedore-master-${{ steps.vars.outputs.short-sha }}
          path: |
            ./dist/*.tar.gz
            ./dist/checksums.txt